version: '3.8'

services:
  app:
    container_name: lovable-ai-app
    build: .
    ports:
      - "3000:3000"
      - "8288:8288"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.docker
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npx inngest-cli dev & 
        npm run dev
      "
