version: '3.8'

services:
  app:
    container_name: lovable-ai-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - E2B_API_KEY=${E2B_API_KEY}
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npx inngest-cli dev & 
        npm run dev
      "
