# This is a config for E2B sandbox template.
# You can use template ID (eek6jq1bgqto6jiltt1k) or template name (my-lovable-ai-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("my-lovable-ai-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("my-lovable-ai-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('my-lovable-ai-test')

team_id = "14211384-ddb0-4eb4-9a4a-8b6ebff73767"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "my-lovable-ai-test"
template_id = "eek6jq1bgqto6jiltt1k"
